javac ./connection/BddObject.java
javac ./payement/Promotion.java
javac ./place/Place.java
javac ./zone/Zone.java
javac ./event/Evenement.java
javac ./reservation/Reservation.java
javac ./client/Client.java
javac ./payement/Payement.java
javac ./place/Placement.java
javac ./reservation/PlaceReserve.java