CREATE TABLE Client (
    idClient VARCHAR PRIMARY KEY,
    nom VARCHAR
);

CREATE SEQUENCE seqClient 
START WITH 1
INCREMENT BY 1;

CREATE TABLE Evenement (
    idEvenement VARCHAR PRIMARY KEY,
    nom VARCHAR
);

CREATE SEQUENCE seqEvenement 
START WITH 1
INCREMENT BY 1;

CREATE TABLE Zone (
    idZone VARCHAR PRIMARY KEY,
    nom VARCHAR
);

CREATE SEQUENCE seqZone
START WITH 1
INCREMENT BY 1;

CREATE TABLE Place (
    idPlace VARCHAR PRIMARY KEY,
    numero VARCHAR
);

CREATE SEQUENCE seqPlace
START WITH 1
INCREMENT BY 1;